/**
 * Synthesis Agent
 * Creates coherent report from findings
 */

import * as crypto from 'crypto';
import { ResearchJob, Finding } from '../types';

export function generateReport(job: ResearchJob): string {
  const { topic, plan, sources, findings } = job;

  const report = `
# Deep Research Report: ${topic}

**Generated**: ${new Date().toISOString()}
**Depth**: ${job.depth}
**Sources analyzed**: ${sources.length}

---

## Executive Summary

This report covers research on "${topic}" based on ${sources.length} sources.

${plan ? `
## Research Plan

### Subtopics Investigated
${plan.subtopics.map((s, i) => `${i + 1}. ${s}`).join('\n')}

### Questions Addressed
${plan.questions.map((q, i) => `${i + 1}. ${q}`).join('\n')}
` : ''}

## Key Findings

${findings.length > 0 ? findings.map(f => `
### ${f.category}
- **Claim**: ${f.claim}
- **Confidence**: ${(f.confidence * 100).toFixed(0)}%
- **Sources**: ${f.sources.join(', ')}
`).join('\n') : '_No findings extracted yet. Run with Claude to analyze sources._'}

## Sources

${sources.map((s, i) => `${i + 1}. [${s.title}](${s.url}) (${s.type})`).join('\n')}

---

## Methodology

1. Topic analysis and planning
2. Multi-source data retrieval
3. Content analysis and extraction
4. Synthesis and report generation
5. Fact verification (if enabled)

---

*Report generated by Elio Deep Research Agent*
`.trim();

  return report;
}

export function extractFindings(content: string, sources: string[]): Finding[] {
  // Placeholder - would use Claude to extract in production
  return [{
    id: crypto.randomUUID(),
    claim: 'Initial research findings pending Claude analysis',
    sources: sources,
    confidence: 0.5,
    category: 'Overview'
  }];
}
