#!/bin/bash
# Nightly CTO Review
# Autonomous code improvement system
# Runs at 02:00 Tbilisi (22:00 UTC)

set -uo pipefail

cd /root/.claude

# Load environment
[ -f "secrets/.env" ] && export $(grep -v '^#' secrets/.env | xargs 2>/dev/null) || true

RUN_ID="cto_$(date +%Y%m%d_%H%M%S)"
LOG_DIR="/root/.claude/logs/nightly"
LOG_FILE="${LOG_DIR}/${RUN_ID}.log"
REPORT_FILE="${LOG_DIR}/${RUN_ID}_report.md"

# Source directories
SRC_DIRS="packages/workflow/src packages/agent-runner/src packages/shared/src apps/worker/src mcp-server/src"

mkdir -p "$LOG_DIR"

log() {
  echo "[$(date '+%H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

notify() {
  local msg="$1"
  if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
    curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
      -d "chat_id=${TELEGRAM_CHAT_ID}" \
      -d "text=${msg}" \
      -d "parse_mode=HTML" >> "$LOG_FILE" 2>&1 || true
  fi
  log "Telegram: $msg"
}

log "=== Nightly CTO Review Started ==="
notify "🌙 <b>Nightly CTO Review Started</b>
Run: ${RUN_ID}"

# Phase 1: Health Check
log "Phase 1: Health Check"
HEALTH_STATUS="✅ HEALTHY"
if ! npx tsx scripts/health-check.ts >> "$LOG_FILE" 2>&1; then
  log "Health check: FAILED"
  HEALTH_STATUS="❌ UNHEALTHY"
  notify "❌ Health check failed!"
else
  log "Health check: PASSED"
fi

# Phase 2: Build
log "Phase 2: Build"
BUILD_STATUS="✅ PASSED"
if ! pnpm build >> "$LOG_FILE" 2>&1; then
  log "Build: FAILED"
  BUILD_STATUS="❌ FAILED"
else
  log "Build: PASSED"
fi

# Phase 3: Code Analysis
log "Phase 3: Code Analysis"

# Count console.log
CONSOLE_LOGS=$(grep -r "console\.log" $SRC_DIRS --include="*.ts" 2>/dev/null | wc -l || echo "0")
log "Console.log count: $CONSOLE_LOGS"

# Count large files
LARGE_FILES=$(find $SRC_DIRS -name "*.ts" -type f 2>/dev/null | xargs wc -l 2>/dev/null | awk '$1 > 200 {count++} END {print count+0}')
log "Large files (>200 lines): $LARGE_FILES"

# Count total lines
TOTAL_LINES=$(find $SRC_DIRS -name "*.ts" -type f 2>/dev/null | xargs cat 2>/dev/null | wc -l || echo "0")
log "Total source lines: $TOTAL_LINES"

# Create report
cat > "$REPORT_FILE" << EOF
# Nightly CTO Review Report
**Run ID:** ${RUN_ID}
**Date:** $(date)

## System Status
| Check | Status |
|-------|--------|
| Health | ${HEALTH_STATUS} |
| Build | ${BUILD_STATUS} |

## Source Code Metrics
| Metric | Value |
|--------|-------|
| Total Lines | ${TOTAL_LINES} |
| Console.log | ${CONSOLE_LOGS} |
| Large Files (>200 lines) | ${LARGE_FILES} |

## Large Files (>200 lines)
EOF

# List large files
find $SRC_DIRS -name "*.ts" -type f 2>/dev/null | while read -r file; do
  lines=$(wc -l < "$file" 2>/dev/null || echo "0")
  if [ "$lines" -gt 200 ]; then
    echo "- \`$file\`: $lines lines" >> "$REPORT_FILE"
  fi
done

cat >> "$REPORT_FILE" << EOF

## Files to Split (>300 lines)
EOF

find $SRC_DIRS -name "*.ts" -type f 2>/dev/null | while read -r file; do
  lines=$(wc -l < "$file" 2>/dev/null || echo "0")
  if [ "$lines" -gt 300 ]; then
    echo "- **$file**: $lines lines - SPLIT NEEDED" >> "$REPORT_FILE"
  fi
done

cat >> "$REPORT_FILE" << EOF

## Console.log Locations
EOF

grep -rn "console\.log" $SRC_DIRS --include="*.ts" 2>/dev/null | head -20 >> "$REPORT_FILE" || echo "None found" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << EOF

## TODO Comments
EOF

grep -rn "TODO\|FIXME" $SRC_DIRS --include="*.ts" 2>/dev/null | head -20 >> "$REPORT_FILE" || echo "None found" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << EOF

## Recommendations

1. **Replace console.log** with \`createLogger()\` from @elio/shared
2. **Split large files** >300 lines into modules
3. **Run pnpm verify** after making changes

---
*Generated by Nightly CTO Review*
EOF

log "Report saved: $REPORT_FILE"

# Phase 4: Summary
log "=== Nightly CTO Review Complete ==="

notify "📊 <b>Nightly CTO Report</b>

🔍 <b>Status:</b>
• Health: ${HEALTH_STATUS}
• Build: ${BUILD_STATUS}

📈 <b>Metrics:</b>
• Lines: ${TOTAL_LINES}
• Console.log: ${CONSOLE_LOGS}
• Large files: ${LARGE_FILES}

📄 ${REPORT_FILE}"

log "Done at $(date)"
